### ISSUE TITLE
[Bug report] commentService do not display 

### ISSUE THREAD

**Issue by Nuyoah0525** [vuepress/core#1582] opened 2024-06-27 08:53 UTC
### Description

"@vuepress/plugin-comment": "^2.0.0-rc.37"

content：

<template #page-bottom>
footer
  CommentService component
</template>

problem:
only footer display
CommentService component do not work

### Reproduction

https://gitee.com/zyh0525/yh-blog/tree/master

### Used Package Manager

yarn

### System Info

```shell
"vuepress": "2.0.0-rc.14"
```

**Comment by typed-sigterm** [comment] 2024-06-30 16:48
`@vuepress/plugin-comment` isn't in this repo.

Off-topic & duplicate of vuepress/ecosystem#210

**Closed** 2024-07-01 09:16 UTC
